"""empty message

Revision ID: 182797b73033
Revises: 9e2e687103a8
Create Date: 2019-06-18 09:39:17.496870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182797b73033'
down_revision = '9e2e687103a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_archived',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('url', sa.String(length=254), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('ip_area', sa.String(length=254), server_default='', nullable=True),
    sa.Column('title', sa.String(length=254), server_default='', nullable=True),
    sa.Column('web_type', sa.String(length=30), server_default='', nullable=False),
    sa.Column('host_dept', sa.String(length=254), server_default='', nullable=True),
    sa.Column('host_type', sa.String(length=50), server_default='', nullable=True),
    sa.Column('industries', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('ai_industries', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('code_language', sa.String(length=50), server_default='', nullable=True),
    sa.Column('http_status', sa.Integer(), server_default='-1', nullable=True),
    sa.Column('http_status_list', sa.String(length=254), server_default='', nullable=True),
    sa.Column('category', sa.String(length=50), server_default='', nullable=True),
    sa.Column('title_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('status_updated', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_website_archived_ai_industries'), 'website_archived', ['ai_industries'], unique=False)
    op.create_index(op.f('ix_website_archived_category'), 'website_archived', ['category'], unique=False)
    op.create_index(op.f('ix_website_archived_create_time'), 'website_archived', ['create_time'], unique=False)
    op.create_index(op.f('ix_website_archived_domain'), 'website_archived', ['domain'], unique=False)
    op.create_index(op.f('ix_website_archived_http_status'), 'website_archived', ['http_status'], unique=False)
    op.create_index(op.f('ix_website_archived_industries'), 'website_archived', ['industries'], unique=False)
    op.create_index(op.f('ix_website_archived_ip'), 'website_archived', ['ip'], unique=False)
    op.create_index(op.f('ix_website_archived_update_time'), 'website_archived', ['update_time'], unique=False)
    op.create_index(op.f('ix_website_archived_url'), 'website_archived', ['url'], unique=True)
    op.create_index(op.f('ix_website_archived_web_type'), 'website_archived', ['web_type'], unique=False)
    op.create_table('website_recycler',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('url', sa.String(length=254), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.BigInteger(), nullable=False),
    sa.Column('city_code', sa.String(length=10), nullable=True),
    sa.Column('region_code', sa.String(length=10), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=False),
    sa.Column('ip_area', sa.String(length=254), server_default='', nullable=True),
    sa.Column('title', sa.String(length=254), server_default='', nullable=True),
    sa.Column('web_type', sa.String(length=30), server_default='', nullable=False),
    sa.Column('host_dept', sa.String(length=254), server_default='', nullable=True),
    sa.Column('host_type', sa.String(length=50), server_default='', nullable=True),
    sa.Column('industries', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('ai_industries', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('code_language', sa.String(length=50), server_default='', nullable=True),
    sa.Column('http_status', sa.Integer(), server_default='-1', nullable=True),
    sa.Column('http_status_list', sa.String(length=254), server_default='', nullable=True),
    sa.Column('category', sa.String(length=50), server_default='', nullable=True),
    sa.Column('title_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('status_updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('reason', sa.String(length=254), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_website_recycler_ai_industries'), 'website_recycler', ['ai_industries'], unique=False)
    op.create_index(op.f('ix_website_recycler_category'), 'website_recycler', ['category'], unique=False)
    op.create_index(op.f('ix_website_recycler_create_time'), 'website_recycler', ['create_time'], unique=False)
    op.create_index(op.f('ix_website_recycler_domain'), 'website_recycler', ['domain'], unique=False)
    op.create_index(op.f('ix_website_recycler_http_status'), 'website_recycler', ['http_status'], unique=False)
    op.create_index(op.f('ix_website_recycler_industries'), 'website_recycler', ['industries'], unique=False)
    op.create_index(op.f('ix_website_recycler_ip'), 'website_recycler', ['ip'], unique=False)
    op.create_index(op.f('ix_website_recycler_update_time'), 'website_recycler', ['update_time'], unique=False)
    op.create_index(op.f('ix_website_recycler_url'), 'website_recycler', ['url'], unique=True)
    op.create_index(op.f('ix_website_recycler_web_type'), 'website_recycler', ['web_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_recycler_web_type'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_url'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_update_time'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_ip'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_industries'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_http_status'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_domain'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_create_time'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_category'), table_name='website_recycler')
    op.drop_index(op.f('ix_website_recycler_ai_industries'), table_name='website_recycler')
    op.drop_table('website_recycler')
    op.drop_index(op.f('ix_website_archived_web_type'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_url'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_update_time'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_ip'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_industries'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_http_status'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_domain'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_create_time'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_category'), table_name='website_archived')
    op.drop_index(op.f('ix_website_archived_ai_industries'), table_name='website_archived')
    op.drop_table('website_archived')
    # ### end Alembic commands ###
