"""empty message

Revision ID: 2846520c81db
Revises: 6dd556890b09
Create Date: 2019-08-05 16:04:36.539493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2846520c81db'
down_revision = '6dd556890b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('spell', sa.String(length=50), server_default='', nullable=True),
    sa.Column('category', sa.String(length=50), server_default='', nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('city', sa.String(length=100), server_default='', nullable=True),
    sa.Column('region', sa.String(length=100), server_default='', nullable=True),
    sa.Column('domain', sa.String(length=200), server_default='', nullable=True),
    sa.Column('domains', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('website_count', sa.Integer(), server_default='0', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_unit_create_time'), 'unit', ['create_time'], unique=False)
    op.create_index(op.f('ix_unit_update_time'), 'unit', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unit_update_time'), table_name='unit')
    op.drop_index(op.f('ix_unit_create_time'), table_name='unit')
    op.drop_table('unit')
    # ### end Alembic commands ###
