"""empty message

Revision ID: 2aa818269200
Revises: 1a049ca1c4cb
Create Date: 2019-07-29 17:12:39.645140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa818269200'
down_revision = '1a049ca1c4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_group',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=50), server_default='', nullable=True),
    sa.Column('spell', sa.String(length=15), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ban_group_create_time'), 'ban_group', ['create_time'], unique=False)
    op.create_index(op.f('ix_ban_group_update_time'), 'ban_group', ['update_time'], unique=False)
    op.create_table('ban_keyword',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('typ', sa.String(length=10), server_default='keyword', nullable=True),
    sa.Column('keyword', sa.String(length=200), server_default='', nullable=True),
    sa.Column('group', sa.String(length=50), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_ban_keyword_create_time'), 'ban_keyword', ['create_time'], unique=False)
    op.create_index(op.f('ix_ban_keyword_update_time'), 'ban_keyword', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ban_keyword_update_time'), table_name='ban_keyword')
    op.drop_index(op.f('ix_ban_keyword_create_time'), table_name='ban_keyword')
    op.drop_table('ban_keyword')
    op.drop_index(op.f('ix_ban_group_update_time'), table_name='ban_group')
    op.drop_index(op.f('ix_ban_group_create_time'), table_name='ban_group')
    op.drop_table('ban_group')
    # ### end Alembic commands ###
