"""empty message

Revision ID: 41aac9c03645
Revises: 3473cc6115c6
Create Date: 2019-06-28 15:51:32.055297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41aac9c03645'
down_revision = '3473cc6115c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_archived_industries', table_name='domain_archived')
    op.drop_column('domain_archived', 'industries')
    op.drop_column('domain_archived', 'tags')
    op.create_unique_constraint(None, 'website_news', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'website_news', type_='unique')
    op.add_column('domain_archived', sa.Column('tags', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.add_column('domain_archived', sa.Column('industries', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True))
    op.create_index('ix_domain_archived_industries', 'domain_archived', ['industries'], unique=False)
    # ### end Alembic commands ###
