"""stop word

Revision ID: 45dffb9e33cb
Revises: 7315980c2b87
Create Date: 2019-08-15 14:39:26.653861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dffb9e33cb'
down_revision = '7315980c2b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stop_word',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('word', sa.String(length=200), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_index(op.f('ix_stop_word_create_time'), 'stop_word', ['create_time'], unique=False)
    op.create_index(op.f('ix_stop_word_update_time'), 'stop_word', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stop_word_update_time'), table_name='stop_word')
    op.drop_index(op.f('ix_stop_word_create_time'), table_name='stop_word')
    op.drop_table('stop_word')
    # ### end Alembic commands ###
