"""empty message

Revision ID: 6c8dadbecfc0
Revises: 5ee531678aca
Create Date: 2019-06-24 14:53:46.446166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8dadbecfc0'
down_revision = '5ee531678aca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('industry', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_unique_constraint(None, 'industry', ['id'])
    op.create_unique_constraint(None, 'industry', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'industry', type_='unique')
    op.drop_constraint(None, 'industry', type_='unique')
    op.alter_column('industry', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
