"""empty message

Revision ID: 7315980c2b87
Revises: 2846520c81db
Create Date: 2019-08-06 17:23:59.162083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7315980c2b87'
down_revision = '2846520c81db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'unit', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unit', type_='unique')
    # ### end Alembic commands ###
