"""empty message

Revision ID: 75418dbc72c4
Revises: 93bbe3de28e3
Create Date: 2019-07-22 15:14:44.119713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75418dbc72c4'
down_revision = '93bbe3de28e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_banned',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_website_banned_create_time'), 'website_banned', ['create_time'], unique=False)
    op.create_index(op.f('ix_website_banned_update_time'), 'website_banned', ['update_time'], unique=False)
    op.create_table('website_duplicated',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_website_duplicated_create_time'), 'website_duplicated', ['create_time'], unique=False)
    op.create_index(op.f('ix_website_duplicated_update_time'), 'website_duplicated', ['update_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_duplicated_update_time'), table_name='website_duplicated')
    op.drop_index(op.f('ix_website_duplicated_create_time'), table_name='website_duplicated')
    op.drop_table('website_duplicated')
    op.drop_index(op.f('ix_website_banned_update_time'), table_name='website_banned')
    op.drop_index(op.f('ix_website_banned_create_time'), table_name='website_banned')
    op.drop_table('website_banned')
    # ### end Alembic commands ###
