"""unit recycler

Revision ID: 997a66fab6a0
Revises: 45dffb9e33cb
Create Date: 2019-08-20 09:48:15.012504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997a66fab6a0'
down_revision = '45dffb9e33cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_recycler',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('spell', sa.String(length=50), server_default='', nullable=True),
    sa.Column('category', sa.String(length=50), server_default='', nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('city', sa.String(length=100), server_default='', nullable=True),
    sa.Column('region', sa.String(length=100), server_default='', nullable=True),
    sa.Column('domain', sa.String(length=200), server_default='', nullable=True),
    sa.Column('domains', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), server_default='{}', nullable=True),
    sa.Column('website_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('reason', sa.String(length=254), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_unit_recycler_create_time'), 'unit_recycler', ['create_time'], unique=False)
    op.create_index(op.f('ix_unit_recycler_update_time'), 'unit_recycler', ['update_time'], unique=False)
    op.create_unique_constraint(None, 'stop_word', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_word', type_='unique')
    op.drop_index(op.f('ix_unit_recycler_update_time'), table_name='unit_recycler')
    op.drop_index(op.f('ix_unit_recycler_create_time'), table_name='unit_recycler')
    op.drop_table('unit_recycler')
    # ### end Alembic commands ###
