"""empty message

Revision ID: 9e2e687103a8
Revises: 46d46606cfaf
Create Date: 2019-06-12 17:53:38.468016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e2e687103a8'
down_revision = '46d46606cfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'city', ['id'])
    op.create_unique_constraint(None, 'domain_archived', ['id'])
    op.add_column('domain_recycler', sa.Column('invalid_time', sa.TIMESTAMP(), nullable=True))
    op.add_column('domain_recycler', sa.Column('subdomain_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('domain_recycler', sa.Column('website_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('domain_recycler', sa.Column('website_count_updated', sa.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'domain_recycler', ['id'])
    op.create_unique_constraint(None, 'province', ['id'])
    op.create_unique_constraint(None, 'region', ['id'])
    op.create_unique_constraint(None, 'setting', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'setting', type_='unique')
    op.drop_constraint(None, 'region', type_='unique')
    op.drop_constraint(None, 'province', type_='unique')
    op.drop_constraint(None, 'domain_recycler', type_='unique')
    op.drop_column('domain_recycler', 'website_count_updated')
    op.drop_column('domain_recycler', 'website_count')
    op.drop_column('domain_recycler', 'subdomain_count')
    op.drop_column('domain_recycler', 'invalid_time')
    op.drop_constraint(None, 'domain_archived', type_='unique')
    op.drop_constraint(None, 'city', type_='unique')
    # ### end Alembic commands ###
