"""empty message

Revision ID: a72a1abbe5ec
Revises: 1a9aa521bdcb
Create Date: 2019-07-25 16:18:33.186788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a72a1abbe5ec'
down_revision = '1a9aa521bdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_news', 'status_updated')
    op.drop_column('website_news', 'title_updated')
    op.drop_column('website_recycler', 'status_updated')
    op.drop_column('website_recycler', 'title_updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_recycler', sa.Column('title_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('website_recycler', sa.Column('status_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('website_news', sa.Column('title_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('website_news', sa.Column('status_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
