"""empty message

Revision ID: efb5bef89fee
Revises: a72a1abbe5ec
Create Date: 2019-07-25 16:22:05.067643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb5bef89fee'
down_revision = 'a72a1abbe5ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website_news', sa.Column('effective_url', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('website_news', 'effective_url')
    # ### end Alembic commands ###
